[W08H08] adding the test if one collection out of the array is empty
MaximilianAnzinger/pgdp2223-tests pull request #176
Opened 2022-12-17 10:03 UTC by Benn1x

i added for the exercise intersection the test if one Collection out of the array is empty the return collection is also empty

2022-12-17 10:08 UTC, ipadmini22 commented
I am not sure that Homework exists ;)

2022-12-17 10:20 UTC, nilsreichardt requested changes
Thanks for writing this test! :)

From my side only the two comments, otherwise LGTM. And you should rename the title to W08H01 :D

2022-12-17 10:20 UTC, nilsreichardt commented on w08h01/test/pgdp/SimpleGenericsTest.java
> +    @Test
```suggestion

    @Test
```

Leave an empty between the tests

2022-12-17 10:20 UTC, nilsreichardt commented on w08h01/test/pgdp/SimpleGenericsTest.java
> +    void intersection2() {
There is already a method called `intersection2`.

```suggestion
    void intersectionWithEmptyList() {
```

Maybe this a better method name?

2022-12-17 10:52 UTC, Benn1x commented
I'm so sorry that i i said [W08H08] i meant [W08H01] sorry

2022-12-17 10:57 UTC, Benn1x commented
i guess now should be everything fine

2022-12-17 11:05 UTC, nilsreichardt approved these changes
Yeah, now it looks good! 😊

2022-12-17 11:05 UTC, merged

2022-12-18 13:05 UTC, MaximilianAnzinger reviewed
🐧