[W09B01] Added tests
MaximilianAnzinger/pgdp2223-tests pull request #185
Opened 2022-12-17 16:59 UTC by HendrikHuebner

2022-12-17 17:26 UTC, nilsreichardt commented on w08h03/test/pgdp/datastructures/UnitTest.java
> +		assertEquals(e.getMessage(), "Trying to call next on an empty QuarternarySearchTreeIterator");
You accidentally added the commits for W08H03 😅 If you need help in removing this from the PR, please let me know 👍

2022-12-17 17:29 UTC, nilsreichardt commented
FYI: To fix the broken `validate-pr-title` check, you need to merge the `main` branch into your `branch` and then just trigger the check again by renaming the title

2022-12-17 23:00 UTC, TheAleWu requested changes

2022-12-17 23:28 UTC, TheAleWu commented
Other than that LGTM

2022-12-18 13:01 UTC, MaximilianAnzinger approved these changes

2022-12-21 11:04 UTC, nilsreichardt commented
Tag me when this is ready to merge

2022-12-21 14:19 UTC, merged

2022-12-22 23:50 UTC, Garfield100 commented
yeah this folder structure is wrong :')