[W09H02]Converted all official Examples from the main method to JUnit Tests
MaximilianAnzinger/pgdp2223-tests pull request #195
Opened 2022-12-21 12:02 UTC by JGStyle

Diese Tests sind eine 1 zu 1 Umwandlung der offiziellen Beispiele in der main method (W09H02). Das alles aber mit debugger und Konsole zu testen ist sehr umständlich. Daher die Tests. Mit diesen Tests passe ich alle tests auf Artemis, kann aber natürlich nicht garantieren, dass alle Tests korrekt sind.

2022-12-21 14:23 UTC, MaximilianAnzinger approved these changes

2022-12-22 08:32 UTC, julian-hartl reviewed
Take a look at #193 and evaluate if it makes sense to rewrite this to fit the given template. Other than that everything is fine.

2022-12-22 08:41 UTC, felixhauptmann requested changes
Please wait for an answer to (this)[https://zulip.in.tum.de/#narrow/stream/1504-PGdP-W09H02/topic/.E2.9C.94.20Rundungsfehler/near/868554] question and change assertions accordingly.

E.g.:

```diff
+assertEquals(16.666666666666668, actual.get("ICE"), 0.001);
-assertEquals(16.666666666666668, actual.get("ICE"));

2022-12-22 09:33 UTC, JGStyle commented
Ich habe nun an der vorgeschlagenen Stelle einen epsilon wert von 0.00001 eingefügt - commit [7842f33](https://github.com/MaximilianAnzinger/pgdp2223-tests/pull/195/commits/7842f33ce78da685350f8487a33a1db49277728c)

Man könnte den epsilon wert auch noch in Zeile 105 und 110 hinzufügen, was meinst du @felixhauptmann ?

2022-12-22 09:36 UTC, felixhauptmann commented
> Ich habe nun an der vorgeschlagenen Stelle einen epsilon wert von 0.00001 eingefügt - commit [7842f33](https://github.com/MaximilianAnzinger/pgdp2223-tests/pull/195/commits/7842f33ce78da685350f8487a33a1db49277728c)
> 
> Man könnte den epsilon wert auch noch in Zeile 105 und 110 hinzufügen, was meinst du @felixhauptmann ?

Ja, bei allen Assertions, die eine fließkommazahl mit einem berechneten Wert vergleichen.

2022-12-22 09:40 UTC, JGStyle commented
Ok, ich habe epsilon an den vorgeschlagenen Stellen hinzugefügt. Ich würde argumentieren, dass der Test averageDelayAt() kein Epsilon braucht, da die zahl ja sowieso weniger genau als der epsilon wert ist.

2022-12-22 10:10 UTC, felixhauptmann commented
> Ok, ich habe epsilon an den vorgeschlagenen Stellen hinzugefügt. Ich würde argumentieren, dass der Test averageDelayAt() kein Epsilon braucht, da die zahl ja sowieso weniger genau als der epsilon wert ist.
> 
> * commit [aa2f3cf](https://github.com/MaximilianAnzinger/pgdp2223-tests/pull/195/commits/aa2f3cf3c50e35d4fae1c90cf3629f97aa114079)

`1.0 != 1.00000001`

2022-12-22 10:41 UTC, JGStyle commented
Alles klar, Ich habe jetzt an allen Stellen, an denen ein Double asserted wird ein Epsilon eingefügt und nochmal einen Verweis auf den entsprechenden Zulip thread hinzugefügt. (Nicht wundern, der erste commit hatte formattierungsprobleme, habe es gefixed) @felixhauptmann

2022-12-22 10:49 UTC, felixhauptmann commented
> Alles klar, Ich habe jetzt an allen Stellen, an denen ein Double asserted wird ein Epsilon eingefügt und nochmal einen Verweis auf den entsprechenden Zulip thread hinzugefügt. (Nicht wundern, der erste commit hatte formattierungsprobleme, habe es gefixed) @felixhauptmann
> 
> [a878706](https://github.com/MaximilianAnzinger/pgdp2223-tests/pull/195/commits/a8787062c4c9048169952e527175a8a63161f54c)

👍

Für einen erneuten review bräuchtest du jemand anderen. Bin gerade auf dem Weg zum Skifahren.

2022-12-25 12:18 UTC, MaximilianAnzinger approved these changes

2022-12-25 12:19 UTC, MaximilianAnzinger commented
Tag me when I can merge it.

2022-12-27 11:53 UTC, JGStyle commented
You can merge it :) @MaximilianAnzinger

2022-12-29 15:54 UTC, merged