[W09B01] SimpleAITest
MaximilianAnzinger/pgdp2223-tests pull request #199
Opened 2022-12-22 14:02 UTC by 3formaggi

Ein paar Tests für SimpleAI in W09B01

2022-12-25 12:23 UTC, MaximilianAnzinger approved these changes

2022-12-25 20:28 UTC, TheAleWu requested changes

2022-12-25 20:28 UTC, TheAleWu commented on w09b01/pgdp/SimpleAITest.java
> +        assertTrue(move.value() >= 1 && move.value() <= 8);
Value kann zwischen 0 und 8 sein, oder gibt es einen Grund für das >= 1 statt >= 0

2022-12-25 22:32 UTC, 3formaggi commented on w09b01/pgdp/SimpleAITest.java
> +        assertTrue(move.value() >= 1 && move.value() <= 8);
hast recht, hab ich geändert

2022-12-26 11:46 UTC, TheAleWu approved these changes
LGTM 👍

2022-12-27 15:38 UTC, merged