[W09H01] Some utility tests for `kidFriendlyTrip()` and `pathLenghtSimple()`
MaximilianAnzinger/pgdp2223-tests pull request #206
Opened 2022-12-30 20:02 UTC by Benn1x

The Test checks at first if `pathLenghtSimple()` works with a simple oneWay and second time with 2 oneWays 
For `kidFriendlyTrip()` i just used the example from artemis.
Ig the `assertArrayEquals()` method i wrote works

2022-12-31 11:27 UTC, MaximilianAnzinger approved these changes

2022-12-31 15:32 UTC, Benn1x commented
I added a few more tests for `furthestAWay()` und `transformToWays()`

2023-01-02 14:34 UTC, Benn1x commented
Here we go again

2023-01-03 10:44 UTC, Benn1x commented
ig now I´m done with passing all these test i passed all artemis test so ig they are right

2023-01-03 14:07 UTC, nilsreichardt requested changes
Hey! 👋  Thanks for your PR!

Could you split all the tests for the tasks into smaller files? For each task a new file, like I did with `ReadWayPoints` and `TransformToWays` (see [here](https://github.com/MaximilianAnzinger/pgdp2223-tests/tree/main/w09h01/test/pgdp/pingutrip)).

The advantage of this is that you can easier run all the tests for one task. Otherwise, you are going to execute all the tests for all tasks which haven't implemented yet.

2023-01-03 15:34 UTC, Benn1x commented
@nilsreichardt i hope know its ok i the test still works and i noticed that there are now 2 transformToWaysTests should i merge these files to getter?

2023-01-03 15:36 UTC, nilsreichardt commented
> @nilsreichardt i hope know its ok i the test still works and i noticed that there are now 2 transformToWaysTests should i merge these files to getter?

Yes, that would be great - thanks! I'm going later to review a second time 👍

2023-01-03 19:57 UTC, Benn1x commented
@nilsreichardt i hope now is everything right

2023-01-04 09:07 UTC, nilsreichardt requested changes
Thanks for the update! 🙏 I added a few more comments. However, when we have resolved the comments, we can merge this 👍

2023-01-04 09:07 UTC, nilsreichardt commented on w09h01/test/pgdp/pingutrip/kidFriedlyTripTest.java
> +import static org.junit.jupiter.api.Assertions.fail;
```suggestion
import static org.junit.jupiter.api.Assertions.assertArrayEquals;
```

We can use the built-in `assertArrayEquals` method

2023-01-04 09:07 UTC, nilsreichardt commented on w09h01/test/pgdp/pingutrip/kidFriedlyTripTest.java
> +    }
```suggestion
```

Code is not used anymore

2023-01-04 09:07 UTC, nilsreichardt commented on w09h01/test/pgdp/pingutrip/kidFriedlyTripTest.java
> +    }
```suggestion
    void kidFriendlyTripTest() {
        List<OneWay> lists = List.of(new OneWay(new WayPoint(0.0, 0.0), new WayPoint(4.0, 0.0)),
                new OneWay(new WayPoint(0.0, 0.0), new WayPoint(1.0, 0.0)),
                new OneWay(new WayPoint(1.0, 0.0), new WayPoint(3.0, 0.0)));

        List<OneWay> expected = List.of();
        List<OneWay> actual = PinguTrip.kidFriendlyTrip(lists);

        assertArrayEquals(expected.toArray(), actual.toArray());
    }
```

This is more readable 👍

2023-01-04 09:07 UTC, nilsreichardt commented on w09h01/test/pgdp/pingutrip/kidFriedlyTripTest.java
> +    }
```suggestion
    void kidFriendlyTripTest2() {
        List<OneWay> lists = List.of(new OneWay(new WayPoint(2.0, 0.0), new WayPoint(4.0, 0.0)),
                new OneWay(new WayPoint(0.0, 0.0), new WayPoint(2.0, 0.0)),
                new OneWay(new WayPoint(0.0, 0.0), new WayPoint(2.0, 0.0)));

        List<OneWay> expected = List.of(new OneWay(new WayPoint(2.0, 0.0), new WayPoint(4.0, 0.0)),
                new OneWay(new WayPoint(0.0, 0.0), new WayPoint(2.0, 0.0)),
                new OneWay(new WayPoint(0.0, 0.0), new WayPoint(2.0, 0.0)));
        List<OneWay> actual = PinguTrip.kidFriendlyTrip(lists);

        assertArrayEquals(expected.toArray(), actual.toArray());
    }
```

This is more readable 👍

2023-01-04 13:07 UTC, Benn1x commented
@nilsreichardt i have commited the suggestions

2023-01-04 15:47 UTC, nilsreichardt commented
> i have commited the suggestions

Have you also pushed them? I'm not seeing them on GitHub o.O

2023-01-04 21:27 UTC, Benn1x commented
> > i have commited the suggestions
> 
> Have you also pushed them? I'm not seeing them on GitHub o.O

Nope

2023-01-04 21:28 UTC, Benn1x commented
But now i have comitted @nilsreichardt

2023-01-05 11:51 UTC, nilsreichardt approved these changes
LGTM ✅

@Benn1x FYI: There were still bugs in your Code. However, I fixed them for your that we can merge it now 👍

2023-01-05 11:52 UTC, merged

2023-01-05 14:26 UTC, Benn1x commented
@nilsreichardt Thx fors debugging