Fix link instructions
MaximilianAnzinger/pgdp2223-tests pull request #23
Opened 2022-11-07 22:03 UTC by thomasw04

Just a fix for the the link cmd

2022-11-08 13:44 UTC, felixhauptmann requested changes
That's not right... the tests are usually in `/test/pgdp` (package pgdp) or `/test`

Therefore the test sourceDir is `test`

2022-11-08 13:53 UTC, MaximilianAnzinger commented
Tell me once both of you agree and I'll accept the PR immediately.

2022-11-08 15:36 UTC, thomasw04 commented
Yes but thats not how the windows command works... Basically in windows the arguments are switched and /test/pgdp does not mean that the folder will be placed in pgdp it does mean that the new folder is called pgdp and a test. (test folder is already present because of gradle

2022-11-08 15:49 UTC, felixhauptmann requested changes
I know how mklink works... it's just that you shouldnt link to a package...

2022-11-08 15:49 UTC, felixhauptmann commented on README.adoc
> +$ mklink /d \path\to\repository\test\pgdp \path\to\repository\aufgabe\test
What about that?

```suggestion
$ mklink /d \path\to\artemis-repository\test \path\to\test-repository\aufgabe\test
```

2022-11-08 15:49 UTC, felixhauptmann commented on README.adoc
> +$ ln -s /path/to/repository/aufgabe/test/pgdp /path/to/repository/test
Same for linux...
```suggestion
$ ln -s /path/to/test-repository/aufgabe/test /path/to/artemis-repository/test
```

2022-11-08 15:51 UTC, thomasw04 commented
You have to, because the test folder already exists because of the gradle script. Because of that the command will fail if you try to link against the test folder.

2022-11-08 16:55 UTC, felixhauptmann commented
Your'e totally right. I missed that. but then we have to link `/path/to/test-repository/aufgabe/test/pgdp` to `/path/to/artemis-repository/test/pgdp`

2022-11-08 20:08 UTC, thomasw04 commented
@MaximilianAnzinger We are done :)

2022-11-09 20:31 UTC, MaximilianAnzinger commented
[🐧](https://emojipedia.org/penguin/)

2022-11-09 20:31 UTC, merged