[W11H03] Fix many issues in W11H03
MaximilianAnzinger/pgdp2223-tests pull request #282
Opened 2023-01-21 19:08 UTC by BjarneHa

This pull-request fixes the following issues:
- `getContacts()` not being allowed to return an empty map
- `testMessageHuge()` output being different on Windows
- `testMessage()` not accepting an arbitrarily long message buffer
- Many assertions not providing reasons for them (Added Zulip links)

2023-01-21 19:20 UTC, nilsreichardt approved these changes
LGTM

I'm waiting for a second review by @felixhauptmann before merging

2023-01-22 00:21 UTC, felixhauptmann requested changes
Other than that LGTM

2023-01-22 00:21 UTC, felixhauptmann commented on w11h03/test/pgdp/networking/SocketTest.java
> +        String lipsumTruncated = Files.readString(Path.of("./test/pgdp/networking/lipsum_truncated.txt")).replace("\r", "");
There are platforms using only '\r' as EOL. This change adds support for these platforms.

```suggestion
        String lipsumTruncated = Files.readString(Path.of("./test/pgdp/networking/lipsum_truncated.txt")).replaceAll("\\r\\n?", "\n");
```

2023-01-22 00:21 UTC, felixhauptmann commented on w11h03/test/pgdp/networking/SocketTest.java
> +        String lipsum = Files.readString(Path.of("./test/pgdp/networking/lipsum.txt")).replace("\r", "");
There are platforms using only '\r' as EOL. This change adds support for these platforms.

```suggestion
        String lipsum = Files.readString(Path.of("./test/pgdp/networking/lipsum.txt")).replaceAll("\\r\\n?", "\n");
```

2023-01-22 00:31 UTC, merged