Added PgdpTestBase and rewrote existing tests to use PgdpTestBase methods
MaximilianAnzinger/pgdp2223-tests pull request #3
Opened 2022-10-28 20:52 UTC by TheAleWu

Ich hab eine Basisklasse für Unit Tests erstellt (`PgdpTestBase`), welche in den Unit Testklassen implementiert werden kann. 

Testen von Rückgabewerten
---
```java
whenCallingMethod(() -> Klasse.methode(..))
     .itShouldReturn(xyz);
```
Hierdurch lässt sich durch eine Methode auf ihren Rückgabewert testen.

Testen von Konsolenausgaben
---
```java
whenCallingMethod(() -> Klasse.methode(..))
     .theConsole().mustContainExactly("Ein Text");
```
Hiermit lässt sich beispielsweise überprüfen, ob die Methode `Klasse.methode(..)` beim Ausführen nur den Text "Ein Text" in System.out schreibt, aber keine weiteren Nachrichten.

Weitere Methoden, die von `.theConsole()` geboten werden:
- `mustContainAnyOf(String...)` 
`Klasse.methode(..)` muss mind. eine der angegebenen Textausgaben in System.out schreiben
- `mustContainAtLeast(String...)` 
`Klasse.methode(..)` muss mind. alle der angegebenen Textausgaben in System.out schreiben
- `hasMessageInLineThatMatches(Integer, String)` 
`Klasse.methode(..)` muss in System.out in Zeile x genau den Text y schreiben

---
Mein Hintergedanke für die Basisklasse:
- Unit Tests lassen sich nun als Sätze formulieren, wodurch vielleicht auch Neulinge Unit Tests schreiben können
- Die Unit Tests geben ausführlichere Fehlermeldungen als die Methoden der org.junit.jupiter.api.Assertions Klasse aus, wodurch es den Nutzern der Tests einfacher fallen sollte, Fehler in ihren Implementierungen nachvollziehen zu können.

Für den Übergang hab ich noch die UnitTests Klasse in W02H01 bestehen lassen, damit man sich selbst entscheiden kann, ob man die org.junit.jupiter.api.Assertions oder meine Implementierung bevorzugt.

2022-10-28 22:04 UTC, nopjar commented on w02h01/test/pgdp/PenguWarmupTest.java
> +    public void checkPenguEvolutions() {
```suggestion
    void checkPenguEvolutions() {
```

2022-10-28 22:04 UTC, nopjar commented on w02h01/test/pgdp/PenguWarmupTest.java
> +    public void checkPenguSum() {
```suggestion
    void checkPenguSum() {
```

2022-10-28 22:05 UTC, nopjar commented on w02h01/test/pgdp/PenguWarmupTest.java
> +    public void checkPenguPermutation() {
```suggestion
    void checkPenguPermutation() {
```

2022-10-28 22:05 UTC, nopjar commented on w02h01/test/pgdp/PenguWarmupTest.java
> +    public void checkPenguPowers() {
```suggestion
    void checkPenguPowers() {
```

2022-10-28 22:08 UTC, nopjar requested changes
LGTM, außer die Konvention bei Unit-Test Methoden

2022-10-28 22:11 UTC, TheAleWu commented
@nopjar Vorschläge wurde noch nachgezogen

2022-10-29 17:23 UTC, closed without merging

2022-10-29 17:24 UTC, TheAleWu commented
Habs zurückgezogen, da der Wartungsaufwand es nicht wert ist (Besonders für Tests wie in W02H02)