[W13H02] Added bytecode tests like W13H01
MaximilianAnzinger/pgdp2223-tests pull request #305
Opened 2023-02-02 01:13 UTC by Leon-hk

Tests the same way as in w13h01

2023-02-03 16:05 UTC, Anatoly03 commented
So wie es aussieht, wird das der letzte PR in diesem Repo sein, congrats, you're lucky!

2023-02-03 16:15 UTC, Leon-hk commented
Dann bist du als Autor aber auch dabei, weil ich von dir geforked hab😂

2023-02-03 19:25 UTC, nilsreichardt commented
@Anatoly03 Ist das ein approval? :D

2023-02-04 09:08 UTC, jakeiridion requested changes
bei mit gehen die tests nur durch wenn ich hier ein .trim() anhänge
assertEquals(o, Integer.parseInt(out.toString().split("\n?\r")[0].trim()));

2023-02-04 12:02 UTC, Leon-hk commented
> bei mit gehen die tests nur durch wenn ich bei w13h01/test/pgdp.minijvm/BonusByteToJavaTest.java am ende ein .trim() anhänge
> 
> assertEquals(o, Integer.parseInt(out.toString().split("\n?\r")[0].trim()));

Welches Betriebssystem nutzt du?

2023-02-04 12:03 UTC, jakeiridion commented
> 

mac os monterey

2023-02-04 12:22 UTC, Leon-hk commented
Würde es ohne das `trim()` auch mit `out.toString().replace("\r", "").split("\n")[0]` funktionieren?

2023-02-04 12:25 UTC, jakeiridion commented
> out.toString().replace("\r", "").split("\n")[0]

Funktioniert! (>'0')>=====WOW

2023-02-04 12:26 UTC, Leon-hk commented
Alles klar, dann änder ich das mal so ab. Vielen Dank für den Hinweis!

2023-02-04 15:21 UTC, nilsreichardt commented
Ist das ready to merge?

2023-02-04 18:27 UTC, Leon-hk commented
Würde sagen ja

2023-02-04 18:42 UTC, merged