[w13b01] added very basic output tests
MaximilianAnzinger/pgdp2223-tests pull request #309
Opened 2023-02-08 22:23 UTC by greenbowser

Added a simple test to compare the output generated by the code to be tested to sample output

2023-02-09 01:17 UTC, nico-lintn requested changes
As windows uses ```\r\n``` as a line seperator (and the expected files only contain ```\n```), every occurence of ```\r``` has to be removed from the actual output.
Without this change ```Assertions.assertEquals()``` will always assert ```false``` on windows.

2023-02-09 01:17 UTC, nico-lintn commented on w13b01/test/pgdp/game/BasicGameTest.java
> +        String actualString = Files.readString(actual.toPath());
```suggestion
        String actualString = Files.readString(actual.toPath()).replaceAll("\r", "");
```

2023-02-09 01:17 UTC, nico-lintn commented on w13b01/test/pgdp/game/BasicGameTest.java
> +        String actualString = Files.readString(actual.toPath());
```suggestion
        String actualString = Files.readString(actual.toPath().replaceAll("\r", ""));
```

2023-02-09 01:17 UTC, nico-lintn commented on w13b01/test/pgdp/game/BasicGameTest.java
> +        String actualString = Files.readString(actual.toPath());
```suggestion
        String actualString = Files.readString(actual.toPath()).replaceAll("\r", "");
```

2023-02-10 10:43 UTC, nilsreichardt commented
can't merge because of a merge conflict

2023-02-10 11:01 UTC, closed without merging