[W05H02] Added structural tests
MaximilianAnzinger/pgdp2223-tests pull request #76
Opened 2022-11-20 19:15 UTC by TheAleWu

Dieses PR fügt Structural Tests für die zu erstellenden Attribute, Konstruktoren und Methoden hinzu. Es wird nur getestet, ob alle notwendigen Elemente (Attribute, Konstruktoren, Methoden) existieren. Zudem wird getestet, ob im Falle von Konstruktoren auch die Reihenfolge der Parameter passt.

2022-11-20 19:16 UTC, TheAleWu commented
⚠️ Ich bitte um ein Review.

2022-11-21 17:00 UTC, DarkbreakerDE requested changes

2022-11-21 17:00 UTC, DarkbreakerDE commented on w05h02/test/pgdp/pingunetwork/structural/GroupStructuralTest.java
> +        expectAttribute("name", 0, String.class, PRIVATE);
Die Reihenfolge der Attribute name, owner und description stimmen nicht der echten Reihenfolge aus dem java file aus Artemis überein. Die echte Reihenfolge ist owner, name, description. Der Fehler stammt von Unerschied zum UML Diagramms.

2022-11-21 17:05 UTC, TheAleWu commented on w05h02/test/pgdp/pingunetwork/structural/GroupStructuralTest.java
> +        expectAttribute("name", 0, String.class, PRIVATE);
Wurde im neusten Commit gefixt.
Hab wegen dieser Inkonsistenz zur Klasse und zur Aufgabenstellung einfach die Indizes von expectAttribute entfernt.

2022-11-21 17:08 UTC, DarkbreakerDE approved these changes
Gefixt

2022-11-21 23:56 UTC, merged